import shanghaiCover from '../assets/shanghai_cover.jpeg'
import tokyoCover from '../assets/tokyo_cover.jpeg'
import scrapbookCover from '../assets/scrapbook_cover.jpg'

export const SAMPLE_PHOTOS = [
  {
    id: 'p-shanghai',
    name: 'Shanghai Skyline',
    location: 'Shanghai, China',
    url: shanghaiCover,
    caption: 'The Bund at dusk ✨',
  },
  {
    id: 'p-tokyo',
    name: 'Tokyo Streets',
    location: 'Tokyo, Japan',
    url: tokyoCover,
    caption: 'Lanterns in Asakusa 🏮',
  },
  {
    id: 'p-journal',
    name: 'Travel Journal Kit',
    location: 'Studio',
    url: scrapbookCover,
    caption: 'Packing list & memories ✈️',
  },
  {
    id: 'p-cafe',
    name: 'Morning Cafe',
    location: 'Paris, France',
    url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=600&q=80',
    caption: 'Fresh croissants & espresso ☕',
  },
  {
    id: 'p-mountains',
    name: 'Alpine Peak',
    location: 'Swiss Alps',
    url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80',
    caption: 'Breath of fresh mountain air 🏔️',
  },
  {
    id: 'p-temple',
    name: 'Kyoto Shrine',
    location: 'Kyoto, Japan',
    url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=600&q=80',
    caption: 'Torii gates pathway ⛩️',
  },
  {
    id: 'p-sunset',
    name: 'Seaside Sunset',
    location: 'Santorini, Greece',
    url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=600&q=80',
    caption: 'Golden hour by the Aegean 🌅',
  },
]

export const STICKER_TEMPLATES = [
  {
    id: 'stk-passport-1',
    category: 'stamps',
    name: 'Passport Control',
    type: 'stamp',
    text: 'PASSPORT CONTROL\nSHANGHAI • ENTRY\nJUL 2026',
    shape: 'circle',
    color: '#587B66',
    rotation: -6,
  },
  {
    id: 'stk-passport-2',
    category: 'stamps',
    name: 'Tokyo Departure',
    type: 'stamp',
    text: 'NARITA INTL\nDEPARTED • TOKYO\n2026.07.24',
    shape: 'oval',
    color: '#D96B43',
    rotation: 7,
  },
  {
    id: 'stk-passport-3',
    category: 'stamps',
    name: 'Air Mail Seal',
    type: 'stamp',
    text: 'PAR AVION\n★ AIR MAIL ★\nPOSTAL SERVICE',
    shape: 'rect',
    color: '#2C4A5E',
    rotation: -4,
  },
  {
    id: 'stk-passport-4',
    category: 'stamps',
    name: 'Explora Certified',
    type: 'stamp',
    text: 'EXPLORA\nAUTHENTIC JOURNEY\n★ VERIFIED ★',
    shape: 'circle',
    color: '#722F37',
    rotation: 5,
  },
  {
    id: 'stk-badge-1',
    category: 'badges',
    name: 'Camera Badge',
    type: 'badge',
    emoji: '📷',
    label: 'SNAP & GO',
    color: '#D96B43',
    bgColor: '#FAF6F0',
  },
  {
    id: 'stk-badge-2',
    category: 'badges',
    name: 'Compass Icon',
    type: 'badge',
    emoji: '🧭',
    label: 'WANDERLUST',
    color: '#2C4A5E',
    bgColor: '#E8EFEA',
  },
  {
    id: 'stk-badge-3',
    category: 'badges',
    name: 'Airplane',
    type: 'badge',
    emoji: '✈️',
    label: 'TAKE OFF',
    color: '#722F37',
    bgColor: '#FAF6F0',
  },
  {
    id: 'stk-badge-4',
    category: 'badges',
    name: 'Coffee Break',
    type: 'badge',
    emoji: '☕',
    label: 'CAFE HOPPING',
    color: '#A68B63',
    bgColor: '#F2EAE1',
  },
  {
    id: 'stk-badge-5',
    category: 'badges',
    name: 'Luggage Tag',
    type: 'badge',
    emoji: '🏷️',
    label: 'CHECKED IN',
    color: '#587B66',
    bgColor: '#E8EFEA',
  },
  {
    id: 'stk-badge-6',
    category: 'badges',
    name: 'Memories Star',
    type: 'badge',
    emoji: '⭐',
    label: '5-STAR MOMENT',
    color: '#C5A880',
    bgColor: '#FAF6F0',
  },
  {
    id: 'stk-badge-7',
    category: 'badges',
    name: 'Postcard',
    type: 'badge',
    emoji: '💌',
    label: 'FROM AFAR',
    color: '#722F37',
    bgColor: '#FAF6F0',
  },
  {
    id: 'stk-badge-8',
    category: 'badges',
    name: 'Train Ride',
    type: 'badge',
    emoji: '🚆',
    label: 'BULLET TRAIN',
    color: '#2C4A5E',
    bgColor: '#E8EFEA',
  },
]

export const TAPE_TEMPLATES = [
  {
    id: 'tape-terracotta',
    name: 'Terracotta Stripes',
    pattern: 'stripes-terracotta',
    color: 'rgba(217, 107, 67, 0.75)',
    accent: '#B54F2B',
  },
  {
    id: 'tape-gold',
    name: 'Gold Vintage',
    pattern: 'dots-gold',
    color: 'rgba(197, 168, 128, 0.8)',
    accent: '#A68B63',
  },
  {
    id: 'tape-sage',
    name: 'Sage Green Plaid',
    pattern: 'grid-sage',
    color: 'rgba(88, 123, 102, 0.75)',
    accent: '#446251',
  },
  {
    id: 'tape-maroon',
    name: 'Classic Maroon',
    pattern: 'plain-maroon',
    color: 'rgba(114, 47, 55, 0.75)',
    accent: '#4A1B21',
  },
  {
    id: 'tape-craft',
    name: 'Kraft Masking Tape',
    pattern: 'craft',
    color: 'rgba(230, 216, 201, 0.85)',
    accent: '#D7C4B1',
  },
]

export const EPHEMERA_TEMPLATES = [
  {
    id: 'eph-sticky-yellow',
    name: 'Yellow Memo',
    type: 'sticky-note',
    bgColor: '#FFFBEB',
    borderColor: '#FDE68A',
    textColor: '#78350F',
    text: 'Note to self:\nTry the street food on the corner tonight! 🍜',
    fontFamily: 'Caveat',
  },
  {
    id: 'eph-sticky-sage',
    name: 'Sage Memo',
    type: 'sticky-note',
    bgColor: '#E8EFEA',
    borderColor: '#C6DDD0',
    textColor: '#2D4A39',
    text: 'Ticket No. 8924\nAdmit One • Museum',
    fontFamily: 'Courier Prime',
  },
  {
    id: 'eph-ticket',
    name: 'Boarding Pass Stub',
    type: 'ticket',
    bgColor: '#FAF6F0',
    borderColor: '#E6D8C9',
    textColor: '#4A1B21',
    text: '✈ FLIGHT EX-2026\nGATE 14 • SEAT 4B\nDESTINATION: MEMORIES',
    fontFamily: 'Courier Prime',
  },
  {
    id: 'eph-wax-seal',
    name: 'Maroon Wax Seal',
    type: 'wax-seal',
    bgColor: '#722F37',
    borderColor: '#4A1B21',
    textColor: '#C5A880',
    text: '✦ E ✦',
    fontFamily: 'Playfair Display',
  },
]

export const DEFAULT_SCRAPBOOKS = [
  {
    id: 'shanghai',
    title: 'Shanghai',
    country: 'China',
    date: 'Jul 2026',
    coverImage: shanghaiCover,
    description: 'Bamboo groves, red torii gates, and matcha tea ceremonies...',
    pages: [
      {
        id: 'p1',
        pageNumber: 1,
        title: 'Arrival in The Bund',
        bgColor: '#FAF6F0',
        bgPattern: 'dots',
        elements: [
          {
            id: 'el-tape-1',
            type: 'tape',
            x: 140,
            y: 45,
            width: 130,
            height: 24,
            rotation: -2,
            tapeId: 'tape-terracotta',
            color: 'rgba(217, 107, 67, 0.75)',
            zIndex: 10,
          },
          {
            id: 'el-photo-1',
            type: 'polaroid',
            x: 60,
            y: 60,
            width: 270,
            rotation: -3,
            imageUrl: shanghaiCover,
            caption: 'The Bund at sunset ✨',
            fontFamily: 'Caveat',
            zIndex: 5,
          },
          {
            id: 'el-stamp-1',
            type: 'stamp',
            x: 460,
            y: 50,
            width: 140,
            height: 140,
            text: 'PASSPORT CONTROL\nSHANGHAI • ENTRY\nJUL 14 2026',
            color: '#587B66',
            shape: 'circle',
            rotation: 8,
            zIndex: 6,
          },
          {
            id: 'el-text-title',
            type: 'text',
            x: 370,
            y: 190,
            width: 320,
            text: 'Day One: Huangpu River',
            fontFamily: 'Playfair Display',
            fontSize: 26,
            fontWeight: 'bold',
            color: '#4A1B21',
            textAlign: 'left',
            rotation: 0,
            zIndex: 7,
          },
          {
            id: 'el-text-desc',
            type: 'text',
            x: 370,
            y: 235,
            width: 330,
            text: 'Walking along the promenade as the city lights flickered to life. The mix of classical colonial architecture on one side and futuristic skyscrapers across the water was surreal.',
            fontFamily: 'Caveat',
            fontSize: 21,
            color: '#44403C',
            textAlign: 'left',
            rotation: 0.5,
            zIndex: 8,
          },
          {
            id: 'el-sticky-1',
            type: 'sticky-note',
            x: 430,
            y: 350,
            width: 230,
            text: '💡 Don’t miss the tea tasting in the French Concession!',
            bgColor: '#FFFBEB',
            color: '#78350F',
            fontFamily: 'Caveat',
            fontSize: 18,
            rotation: -3,
            zIndex: 9,
          },
          {
            id: 'el-badge-1',
            type: 'badge',
            x: 80,
            y: 400,
            emoji: '📷',
            label: 'SHANGHAI 2026',
            color: '#D96B43',
            bgColor: '#FAF6F0',
            rotation: 6,
            zIndex: 11,
          },
        ],
      },
      {
        id: 'p2',
        pageNumber: 2,
        title: 'Yu Garden & Teahouses',
        bgColor: '#FDFBF7',
        bgPattern: 'plain',
        elements: [
          {
            id: 'el-p2-title',
            type: 'text',
            x: 60,
            y: 40,
            width: 400,
            text: 'Yu Garden Serenity 🌿',
            fontFamily: 'Playfair Display',
            fontSize: 28,
            fontWeight: 'bold',
            color: '#722F37',
            textAlign: 'left',
            rotation: -1,
            zIndex: 4,
          },
          {
            id: 'el-p2-text',
            type: 'text',
            x: 60,
            y: 95,
            width: 320,
            text: 'Stepping into the 400-year-old Ming dynasty garden felt like traveling through time. Koi ponds, arched stone bridges, and the soothing sound of bamboo fountains.',
            fontFamily: 'Caveat',
            fontSize: 22,
            color: '#292524',
            textAlign: 'left',
            rotation: 0,
            zIndex: 5,
          },
          {
            id: 'el-p2-photo',
            type: 'polaroid',
            x: 410,
            y: 60,
            width: 280,
            rotation: 4,
            imageUrl: shanghaiCover,
            caption: 'Classical pavilions & koi ponds',
            fontFamily: 'Caveat',
            zIndex: 6,
          },
          {
            id: 'el-p2-stamp',
            type: 'stamp',
            x: 100,
            y: 320,
            width: 130,
            height: 130,
            text: 'EXPLORA\nAUTHENTIC JOURNEY\n★ YU GARDEN ★',
            color: '#2C4A5E',
            shape: 'oval',
            rotation: -7,
            zIndex: 7,
          },
          {
            id: 'el-p2-ticket',
            type: 'ticket',
            x: 270,
            y: 330,
            width: 220,
            text: '🎫 ADMIT ONE\nYU GARDEN PAVILION\nENTRY: 10:30 AM',
            bgColor: '#FAF6F0',
            borderColor: '#E6D8C9',
            textColor: '#4A1B21',
            fontFamily: 'Courier Prime',
            rotation: 2,
            zIndex: 8,
          },
        ],
      },
      {
        id: 'p3',
        pageNumber: 3,
        title: 'Street Food & Night Markets',
        bgColor: '#E8EFEA',
        bgPattern: 'grid',
        elements: [
          {
            id: 'el-p3-title',
            type: 'text',
            x: 220,
            y: 50,
            width: 360,
            text: 'Flavors of the Night 🥟',
            fontFamily: 'Playfair Display',
            fontSize: 30,
            fontWeight: 'bold',
            color: '#2D4A39',
            textAlign: 'center',
            rotation: 0,
            zIndex: 3,
          },
          {
            id: 'el-p3-tape',
            type: 'tape',
            x: 280,
            y: 35,
            width: 140,
            height: 24,
            rotation: 1,
            color: 'rgba(88, 123, 102, 0.75)',
            zIndex: 10,
          },
          {
            id: 'el-p3-text',
            type: 'text',
            x: 100,
            y: 120,
            width: 560,
            text: 'Steaming Shengjianbao (pan-fried buns), hot scallion pancakes, and sweet osmanthus fermented rice cakes. The sights and aromas were unforgettable!',
            fontFamily: 'Caveat',
            fontSize: 23,
            color: '#1F2937',
            textAlign: 'center',
            rotation: 0,
            zIndex: 4,
          },
          {
            id: 'el-p3-sticky',
            type: 'sticky-note',
            x: 260,
            y: 230,
            width: 250,
            text: '⭐️ Ranking:\n1. Pan-fried buns\n2. Xiao Long Bao\n3. Jasmine bubble tea',
            bgColor: '#FFFBEB',
            color: '#78350F',
            fontFamily: 'Caveat',
            fontSize: 20,
            rotation: -2,
            zIndex: 6,
          },
        ],
      },
    ],
  },
  {
    id: 'tokyo',
    title: 'Tokyo',
    country: 'Japan',
    date: 'Jul 2026',
    coverImage: tokyoCover,
    description: 'Gelato at sunset, exploring ancient ruins and hidden cobblestone alleys.',
    pages: [
      {
        id: 'tp1',
        pageNumber: 1,
        title: 'Shibuya Crossing & Lights',
        bgColor: '#FAF6F0',
        bgPattern: 'dots',
        elements: [
          {
            id: 'el-tp1-photo',
            type: 'polaroid',
            x: 70,
            y: 60,
            width: 280,
            rotation: 2,
            imageUrl: tokyoCover,
            caption: 'Tokyo Night Lights 🌃',
            fontFamily: 'Caveat',
            zIndex: 5,
          },
          {
            id: 'el-tp1-tape',
            type: 'tape',
            x: 150,
            y: 45,
            width: 120,
            height: 24,
            rotation: -3,
            color: 'rgba(44, 74, 94, 0.75)',
            zIndex: 10,
          },
          {
            id: 'el-tp1-title',
            type: 'text',
            x: 390,
            y: 70,
            width: 320,
            text: 'Kon’nichiwa Tokyo!',
            fontFamily: 'Playfair Display',
            fontSize: 28,
            fontWeight: 'bold',
            color: '#4A1B21',
            textAlign: 'left',
            rotation: 0,
            zIndex: 4,
          },
          {
            id: 'el-tp1-text',
            type: 'text',
            x: 390,
            y: 120,
            width: 320,
            text: 'Arrived at Haneda, caught the monorail straight to Shinjuku. The energy here is electrifying yet so peaceful and organized.',
            fontFamily: 'Caveat',
            fontSize: 22,
            color: '#44403C',
            textAlign: 'left',
            rotation: 0,
            zIndex: 5,
          },
          {
            id: 'el-tp1-stamp',
            type: 'stamp',
            x: 430,
            y: 280,
            width: 140,
            height: 140,
            text: 'NARITA INTL\nENTRY • TOKYO\n2026.07.18',
            color: '#D96B43',
            shape: 'oval',
            rotation: 6,
            zIndex: 6,
          },
        ],
      },
      {
        id: 'tp2',
        pageNumber: 2,
        title: 'Asakusa & Senso-ji',
        bgColor: '#FDFBF7',
        bgPattern: 'plain',
        elements: [
          {
            id: 'el-tp2-title',
            type: 'text',
            x: 60,
            y: 50,
            width: 400,
            text: 'Senso-ji Temple & Nakamise',
            fontFamily: 'Playfair Display',
            fontSize: 26,
            fontWeight: 'bold',
            color: '#722F37',
            textAlign: 'left',
            zIndex: 4,
          },
          {
            id: 'el-tp2-text',
            type: 'text',
            x: 60,
            y: 100,
            width: 340,
            text: 'Incense smoke curling through the grand gates. Picked up freshly grilled ningyo-yaki and an omikuji fortune (Good Luck!).',
            fontFamily: 'Caveat',
            fontSize: 22,
            color: '#333',
            zIndex: 5,
          },
        ],
      },
    ],
  },
]
